import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const generalSans = localFont({
	src: [
		{
			path: "../fonts/general-sans/GeneralSans-Variable.woff2",
			weight: "100 900",
			style: "normal",
		},
		{
			path: "../fonts/general-sans/GeneralSans-VariableItalic.woff2",
			weight: "100 900",
			style: "italic",
		},
	],
	variable: "--font-general-sans",
	display: "swap",
});

const cabinetGrotesk = localFont({
	src: "../fonts/cabinet-grotesk/CabinetGrotesk-Variable.woff2",
	weight: "100 900",
	variable: "--font-cabinet-grotesk",
	style: "normal",
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"antialiased",
					generalSans.variable,
					cabinetGrotesk.variable,
				)}
			>
				{children}
			</body>
		</html>
	);
}
