import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

/**
 * Font Configuration - Geist Sans (Primary Typography)
 *
 * Geist is a modern, geometric sans-serif font optimized for readability
 * across digital interfaces. Perfect for UI text, headings, and body content.
 */
const geistSans = Geist({
	/**
	 * CSS custom property name for the font family
	 * Creates --font-geist-sans variable accessible throughout the app
	 * Usage in CSS: font-family: var(--font-geist-sans)
	 */
	variable: "--font-geist-sans",

	/**
	 * Character subsets to download
	 * 'latin' covers standard English characters and common symbols
	 * Reduces bundle size by excluding unnecessary character sets
	 */
	subsets: ["latin"],
});

/**
 * Font Configuration - Geist Mono (Code Typography)
 *
 * Geist Mono is a monospace font with consistent character widths
 * Ideal for code blocks, technical content, and data display
 */
const geistMono = Geist_Mono({
	/**
	 * CSS custom property for monospace font
	 * Creates --font-geist-mono variable for code and technical text
	 */
	variable: "--font-geist-mono",

	/**
	 * Latin character subset only
	 * Sufficient for code and technical documentation
	 */
	subsets: ["latin"],
});

/**
 * Application Metadata
 *
 * Defines SEO and browser information for the entire application
 * This metadata applies to all pages unless overridden at the page level
 */
export const metadata: Metadata = {
	/**
	 * Page title displayed in browser tab and search results
	 * Consider updating to reflect your actual application name
	 */
	title: "Create Next App",

	/**
	 * Meta description for SEO and social sharing
	 * Should be 150-160 characters and describe your app's purpose
	 */
	description: "Generated by create next app",

	/**
	 * Additional metadata you might want to add:
	 *
	 * viewport: "width=device-width, initial-scale=1",
	 * robots: "index, follow",
	 * authors: [{ name: "Your Name" }],
	 * keywords: ["keyword1", "keyword2"],
	 * openGraph: {
	 *   title: "Your App Name",
	 *   description: "Your app description",
	 *   type: "website",
	 *   locale: "en_US",
	 * },
	 */
};

/**
 * Root Layout Component
 *
 * The foundational layout that wraps ALL pages in the application
 * Defines the basic HTML structure, fonts, and global styling
 * This component renders on every route in your Next.js app
 */
export default function RootLayout({
	children,
}: Readonly<{
	/**
	 * Page content that gets rendered inside this layout
	 * Represents the actual page components and their content
	 */
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* 
				Template literal combining multiple class names:
				- ${geistSans.variable}: Makes --font-geist-sans available via CSS custom property
				- ${geistMono.variable}: Makes --font-geist-mono available via CSS custom property  
				- antialiased: Tailwind utility for smooth font rendering across browsers
				
				The fonts are now accessible throughout your CSS:
				- font-family: var(--font-geist-sans) for UI text
				- font-family: var(--font-geist-mono) for code blocks
				*/}

				{/* 
				All page content renders here
				This includes pages, components, and any nested layouts
				*/}
				{children}
			</body>
		</html>
	);
}
